# Generated by Django 4.1.3 on 2022-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=25)),
            ],
        ),
    ]
